INSERT INTO xxl_job.xxl_job_log (job_group, job_id, executor_address, executor_handler, executor_param,
                                 executor_sharding_param, executor_fail_retry_count, trigger_time, trigger_code,
                                 trigger_msg, handle_time, handle_code, handle_msg, alarm_status)
VALUES (1, 1, NULL, 'demoJobHandler', '', NULL, 0, '2021-11-16 17:30:00', 500,
        '任务触发类型：Cron触发<br>调度机器：192.168.0.101<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>',
        NULL, 0, NULL, 3),
       (1, 1, NULL, 'demoJobHandler', '', NULL, 0, '2021-11-19 17:30:00', 500,
        '任务触发类型：Cron触发<br>调度机器：192.168.0.101<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>',
        NULL, 0, NULL, 3),
       (1, 1, NULL, 'demoJobHandler', '', NULL, 0, '2021-11-20 17:30:00', 500,
        '任务触发类型：Cron触发<br>调度机器：192.168.0.101<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>',
        NULL, 0, NULL, 3),
       (1, 1, NULL, 'demoJobHandler', '', NULL, 0, '2021-11-21 17:30:00', 500,
        '任务触发类型：Cron触发<br>调度机器：192.168.0.101<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>',
        NULL, 0, NULL, 3),
       (1, 1, NULL, 'demoJobHandler', '', NULL, 0, '2021-11-24 17:30:00', 500,
        '任务触发类型：Cron触发<br>调度机器：192.168.0.101<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>',
        NULL, 0, NULL, 3),
       (1, 1, NULL, 'demoJobHandler', '', NULL, 0, '2021-11-25 17:30:00', 500,
        '任务触发类型：Cron触发<br>调度机器：192.168.0.101<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>',
        NULL, 0, NULL, 3),
       (1, 1, NULL, 'demoJobHandler', '', NULL, 0, '2021-12-02 17:30:00', 500,
        '任务触发类型：Cron触发<br>调度机器：192.168.0.101<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>',
        NULL, 0, NULL, 3),
       (1, 1, NULL, 'demoJobHandler', '', NULL, 0, '2021-12-13 17:30:00', 500,
        '任务触发类型：Cron触发<br>调度机器：192.168.0.101<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>',
        NULL, 0, NULL, 3);